-- Insert data into the Topics table
INSERT INTO Topics (courseid, Topictitle)
VALUES
(1, 'Variables and Data Types'),
(1, 'Control Flow'),
(1, 'Functions'),
(2, 'Relational Database Concepts'),
(2, 'SQL Queries'),
(2, 'Normalization'),
(3, 'HTML Basics'),
(3, 'CSS Fundamentals'),
(3, 'JavaScript Basics'),
(4, 'Firewalls'),
(4, 'Intrusion Detection Systems'),
(4, 'Encryption Techniques'),
(5, 'Search Algorithms'),
(5, 'Machine Learning Algorithms'),
(5, 'Neural Networks'),
(6, 'Data Collection and Cleaning'),
(6, 'Statistical Analysis'),
(6, 'Machine Learning Models'),
(7, 'Cyber Threats and Vulnerabilities'),
(7, 'Security Policies and Procedures'),
(7, 'Risk Management'),
(8, 'Mobile UI Design'),
(8, 'Native vs. Hybrid Apps'),
(8, 'API Integration'),
(9, 'Software Development Life Cycle'),
(9, 'Version Control Systems'),
(9, 'Agile Methodologies'),
(10, 'Linear Regression'),
(10, 'Classification Algorithms'),
(10, 'Clustering Techniques');
go